### ISSUE TITLE
Complie Problem

### ISSUE THREAD

**Issue by HsiaoYeekwan** [loryhndol/LowpolyBuildings#1]
Thanks for the code for reference！
But I encountered the following problem when compiling.
My environment configuration is as follows:
CGAL 5.5.2, boost 1.71.0 ,VS2019, cmake 3.25.3

![image](https://github.com/loryhndol/LowpolyBuildings/assets/25145401/11400012-3eba-4be5-9813-e3e61268d8b9)
And I can run CGAL examples correctly, Could you please provide your dependency version for reference?

**Comment by loryhndol** [comment]
I tried to fix the pb by using template to carry different precision of mesh representation in `calculateParetoSet.cc`. If there is something new, plz let me know.
