### ISSUE TITLE
Huge amount of calculation & CGAL error

### ISSUE THREAD

**Issue by HsiaoYeekwan** [loryhndol/LowpolyBuildings#2]
Thanks for your reply~
When I run using resources\bunny10K.obj, there are 'Direction Set' contains so many vector that a huge amount of calculation.

(eg: The for loop will be executed   49924100* 49924100 times)
![image](https://github.com/loryhndol/LowpolyBuildings/assets/25145401/e9e58b74-9985-4a44-9380-418b90a9cbe7)

And I also encountered a CGAL error when I delete some values in 'Direction Set':
![image](https://github.com/loryhndol/LowpolyBuildings/assets/25145401/834112e6-9a48-4206-aa10-e9453ac1c4c6)

**Comment by loryhndol** [comment]
Indeed, this is a bug. The old version of code made mistakes when `fitPlanesFromRegions`, 
the [link to code](https://github.com/loryhndol/LowpolyBuildings/blob/cadf2af42f491d8c0fb2da48850ae2237222d423/algorithms/src/VisualHullConstructor.cc#L240C16-L254) shows the correct sequence to execute. (outside the inner loop)
