### ISSUE TITLE
run crash in "glGenVertexArrays(vaoSize, VAO.data())"

### ISSUE THREAD

**Issue by klxqlehua** [loryhndol/LowpolyBuildings#3]
hello, I build this project on Mac.
when I run it, it always crash on the code of "glGenVertexArrays(vaoSize, VAO.data())" which is in the function of "OpenGLRenderer::snapshot". 
<img width="594" alt="image" src="https://github.com/loryhndol/LowpolyBuildings/assets/4538290/c9293079-201d-4f2b-a86c-c5e58189cdfe">
The Exception is "EXC_BAD_ACCESS(code=1, address=0x0)"
Do you know why the address is 0x0? Could you solve this problem?
thanks.

**Comment by loryhndol** [comment]
It seems like that the `VAO.data()` is a null pointer. Could you please check whether the model is loaded successfully?

**Comment by klxqlehua** [comment]
I use glew replace glad and set glewExperimental = GL_TRUE; 
and then glewInit(); 
At last this crash solved.

**Comment by klxqlehua** [comment]
My workmate came across the same problem on linux, so I suspect you can run success on windows?
Can you please describe the dependencies that consist of versions in detail in README.md?
Thanks.

**Comment by loryhndol** [comment]
> My workmate came across the same problem on linux, so I suspect you can run success on windows? Can you please describe the dependencies that consist of versions in detail in README.md? Thanks.

Thanks for your suggestions . I have updated the README

**Comment by klxqlehua** [comment]
Ok, thank you.
